# Generated by Django 3.2.5 on 2021-07-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
