# Generated by Django 3.2.5 on 2021-07-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_product_url_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url_image',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='null', upload_to='images'),
        ),
    ]
